# -- Book settings --
title: "My Awesome Databricks Book" # The title of the book
author: "Z. Had" # The author's name
copyright: "2026" # Copyright year

# -- Execution settings --
# Control whether notebooks are executed when the book is built
execute:
  execute_notebooks: "off" # Set to "off" to prevent execution during the build, "force" to run always
  timeout: 60 # Maximum time a single cell is allowed to run (in seconds)

# -- HTML output settings --
html:
  use_repository_button: true # Add a button linking to your source repository
  use_issues_button: true # Add a button linking to your issue tracker
  use_edit_page_button: true # Add a button to edit the page content directly on GitHub

# -- Repository settings --
repository:
  url: https://github.com/haddadz/my-databricks-book # The URL to your book's repository
  branch: main # The branch on which the book's source code lives
  # Path to the directory where the book content is hosted (e.g. content/)
  path_to_book: "content" 
